### ISSUE TITLE
[Idea] Remove dependency on automake/autoconf

### ISSUE THREAD

**Issue by ankane** [jasonroelofs/rice#128] opened 2020-05-29 23:43 UTC
Hey, just wanted to suggest removing the dependency on automake if possible. Currently, Mac users need to run:

```sh
brew install automake
```

to install Rice (which also installs autoconf).

**Comment by jasonroelofs** [comment] 2020-06-01 19:30
Yeah, while it's normally a good assumption that autoconf and automake already exist on any system trying to compile code, that's definitely less true as time goes on. I'm not sure what it would take but it's not a trivial thing to swap out, and I'm not sure what a replacement would look like. There's a decent bit of logic in there around what version of Ruby we're building against as well as what some C and C++ level feature detection. It's possible some of that is no longer strictly necessary?

**Comment by ankane** [comment] 2020-06-01 20:18
I'm not super familiar with C/C++, but I think it could be handled in `extconf.rb`, which will have access to `RUBY_VERSION` and `RbConfig::CONFIG`. The Rice code could also use `__cplusplus` and [feature macros](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations) as needed.

**Comment by CAMOBAP** [comment] 2021-01-12 15:43
### Intro

We use `rice` for [`expressir`](https://github.com/lutaml/expressir). Because of a long compilation of the gem, we decided to push platform gems (with prebuilt native extension).

AFAIK 'standard' way to accomplish this is to use `rake-compiler` + `rake-compiler-dock`. But here I faced with a problem: _gem will be installed and compiled for a build machine, not for a host one_.

After several days of research, I have tried simply to include `rice` source code into `expressir`'s compilation flow, and... surprisingly it just works for all platforms: windows, macos and linux ! (I have tried rice-2.2.0) 

### Сonclusions

 - As far as I understand [the license of `rice` allows this](https://github.com/jasonroelofs/rice/blob/master/COPYING)
 - Isn't clear why automaker tools need at all, maybe I missing something important but so far, everything works

### Implementation

 - Here is [extconf.rb](https://github.com/lutaml/expressir/blob/master/ext/express-parser/extconf.rb#L21-L35)
 - [rakelib/cross-ruby.rake](https://github.com/lutaml/expressir/blob/master/rakelib/cross-ruby.rake) (inspired by [nogokiri's solution](https://github.com/sparklemotion/nokogiri/blob/master/rakelib/cross-ruby.rake))

**Comment by jasonroelofs** [comment] 2021-01-12 23:56
@CAMOBAP If I follow you correctly, the problem is that because you're depending on rice, which requires compilation on installation, that conflicts with trying to build and publish a platform-specific gem (e.g. two layers of compilation)?

Have you tried having `rice` as `add_development_dependency` instead? That should at least keep it from trying to build rice on the installation of your gem. I have nothing against what you're doing right now, good to hear that you figured out something that works!

**Comment by CAMOBAP** [comment] 2021-01-13 07:01
> If I follow you correctly, the problem is that because you're depending on rice, which requires compilation on installation, that conflicts with trying to build and publish a platform-specific gem (e.g. two layers of compilation)?

Yep, exactly. To be on the same page it's not a problem of `rice` gem, it's more related to the tooling, I'm not sure that there is a way to achieve this at all

> Have you tried having rice as add_development_dependency instead?

Good suggestion, but we still need to upload 'plain-ruby' version of the gem (just in case), so we keep this dependency for 'ruby' gem, but [strip it for all platform gems](https://github.com/lutaml/expressir/blob/master/rakelib/cross-ruby.rake#L306)

----

Thank you @jasonroelofs for work on this awesome project (I'm a huge c++ fan)!

To be on the same page, my point was that if we can compile `rice` without any extra build configuration (specific compilation options), why do we need this complex configuration at all?

P.S. I definitely don't see the whole picture so maybe I'm skipping something very important

**Comment by jasonroelofs** [comment] 2021-01-13 13:25
That is a good point. I will review our use of automake/autoconf to see what exactly we're getting out of it and see if we can just drop that part of the project entirely.

**Comment by jasonroelofs** [comment] 2021-03-14 20:02
We can close this out, `master` and the upcoming 4.x release line no longer requires automake/autoconf!

**Closed** 2021-03-14 20:02 UTC
