### ISSUE TITLE
Make: Fix parallel build

### ISSUE THREAD

**Issue by marvin2k** [jasonroelofs/rice#71] opened 2014-06-24 08:35 UTC
Hi,

while implementing a bitbake recipe for rice, I fixed the parallel build process on a current Debian Testing. See this [gist](https://gist.github.com/marvin2k/4c651c8ed792e6060961#file-fix-recursive-makefile-patch). Two problems: calling `make` in a Makefile directly will break recursive make, its better to use `${MAKE}`. And some dependencies were a bit mashed up. It compiles now with `make -j9`.

No fork+pull-request though ;-) sorry for that...

Ah, one other thing: Maybe it's worth mentioning that the project is autotools-based (nice!), but the invocation of `make all` needs `DESTDIR` set in case one is going to use it in the `make install` phase. Otherwise, some calls to ruby in the `make all` phase will fail to create the correct Makefiles using `mkmf.rb`. Maybe thats a general issue for `mkmf.rb`?

**Comment by mintar** [comment] 2015-05-07 12:37
Parallel make of rice is broken also when using gem. On Ubuntu 14.04, the following breaks:

    export MAKEFLAGS=-j8
    gem install rice

The error log is [here](https://gist.github.com/mintar/d9eca9a1d786edca8b3e). I haven't tried @marvin2k 's patch, but I suspect it would help.

**Comment by jasonroelofs** [comment] 2015-05-10 21:06
Thanks for the example and output, I'll take a look.

**Comment by mintar** [comment] 2015-10-15 11:56
Unfortunately, b301d06 didn't fix this for me. I can still reproduce the error with pretty much the same result as in my comment from May 7.

**Comment by jasonroelofs** [comment] 2015-10-15 13:03
Hmm maybe it's a Mac vs Linux thing? It works great on my Mac now, what system are you running?

**Comment by mintar** [comment] 2015-10-15 13:04
Could be, I'm running Ubuntu 14.04.

**Comment by jasonroelofs** [comment] 2015-10-15 23:47
Hmm I can't make it fail, though I've got Ubuntu 15.10 running right now. I'll get a 14.04 box going too and see if that's the difference.

**Comment by mintar** [comment] 2015-10-16 14:01
I've created a Vagrantfile for you so that you can exactly reproduce my problem. Step-by-step instructions:

* Install vagrant from web site: http://www.vagrantup.com/downloads (won't work with old versions)
* Install virtualbox (I used the one from the Ubuntu 14.04 repos)
* copy my [Vagrantfile](https://gist.githubusercontent.com/mintar/242782dc100b3e5f26e2/raw/6628f24dc3cf70d4ed624feebff8dea8c32948ad/Vagrantfile) to a directory of your choosing, cd to that dir
* `you@host:~$ vagrant up`
* `you@host:~$ vagrant ssh`
* `vagrant@vagrant-ubuntu-trusty-64:~$ git clone https://github.com/jasonroelofs/rice.git /home/vagrant/rice`
* `vagrant@vagrant-ubuntu-trusty-64:~$ cd rice`
* `vagrant@vagrant-ubuntu-trusty-64:~$ gem install -i /tmp rice`

This will reproduce the problem, since I've already included `echo 'export MAKEFLAGS=-j8' >> /home/vagrant/.bashrc` in the Vagrantfile. If you do `unset MAKEFLAGS` before `gem install`, it builds fine.

I would fix the problem myself if I could, but I tried for several hours yesterday and gave up.

**Comment by jasonroelofs** [comment] 2015-10-16 17:22
@mintar There's a small problem with the steps you've given here. The last line, `gem install` isn't installing from local but from rubygems. You need to `gem build rice.gemspec` then `gem install rice-1.7.0.gem` which from all my testing, passes fine with `-j` set.

**Comment by mintar** [comment] 2015-10-17 18:48
Great, thanks for clearing that up! That also explains why all my attempts at fixing this didn't do anything... I'm not very fluent in ruby. I can confirm that this builds fine now, so you actually fixed the bug. I think we can close this issue. Thanks!

**Comment by jasonroelofs** [comment] 2015-10-17 19:55
Awesome, thanks for confirming!

**Closed by jasonroelofs** 2015-10-17 19:55 UTC

**Comment by marvin2k** [comment] 2015-10-19 09:12
:thumbsup:
